# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: testing-service

plugins:
 - serverless-plugin-encrypted
 - serverless-plugin-scripts


custom:
  stage: "${opt:stage, self:provider.stage}"
  kmsKeyId: ${self:custom.stage}-testing-service
  encrypted:
    AWS_ACCESS: ${env:ACCESS_KEY}
    AWS_SECRET: ${env:ACCESS_SECRET}
  scripts:
    commands:
      stage : echo the current stage is ${self:custom.stage}
    hooks:
      slstats:slstats : echo stats run

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs6.10
  memorySize : 128
  environment : ${file(env/secrets.yml):${self:custom.stage}}
  tracing : true
  timeout : 30
  profile : dev
  tag : testing

functions:
  env:
    handler: functions/env.handler
    description : used for testing environment variables
    timeout : 120
    profile : dev
    environment :
      ACCESS_KEY: 'AKIAI6ZQ4DDPWRTBQYIA'
      ACCESS_SECRET : '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'



#resources:
#  Resources:
#    TestTopic:
#      Type: AWS::SNS::Topic
#      Properties:
#        TopicName : "weather-fetch-error-topic"


