service: quotebot

plugins:
  - serverless-plugin-encrypted
  - serverless-plugin-tracing

custom:
  stage: "${opt:stage, self:provider.stage}"
  kmsKeyId: ${self:provider.stage}-quotebot
  encrypted:
    SECRET_APP_ID: ${file(env/facebook.yml):${self:custom.stage}:APP_ID}
    SECRET_APP_KEY: ${file(env/facebook.yml):${self:custom.stage}:APP_SECRET}

provider:
  name: aws
  runtime: nodejs6.10
  memorySize : 128
  tracing : true
  environment:
    FB_ID: ${self:custom.encrypted.SECRET_APP_ID}
    FB_SECRET: ${self:custom.encrypted.SECRET_APP_KEY}
  timeout : 30
  tag : testing
  iamRoleStatements:
    - Effect: "Allow" # xray permissions (required)
      Action:
        - "xray:PutTraceSegments"
        - "xray:PutTelemetryRecords"
      Resource:
        - "*"

functions:
  webhook:
    handler: handler.webhook
    events:
      - http:  
          path: webook
          method: GET
          integration: lambda
      - http:
          path: webook
          method: POST
          integration: lambda
